### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by extremeshok** [ascendantcom/fts-elasticsearch#8]
Appears elasticsearch will always fail after a few mins of running the indexer.

Could be the way the indexer is sending too much data for elasticsearch to process ?

We have 64GB ram.. and 8GB dedicated to elasticsearch

```
doveadm index -A *
```

Errors

```
[9eaabd2e0fbd73536b500000c90125ce][[9eaabd2e0fbd73536b500000c90125ce][4]] IndexFailedEngineException[Index failed for [mail#2867]]; nested: OutOfMemoryError[Java heap space];
    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:473)
    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:571)
    at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
    at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1073)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at org.apache.lucene.index.DocumentsWriterPerThread$IntBlockAllocator.getIntBlock(DocumentsWriterPerThread.java:572)
    at org.apache.lucene.util.IntBlockPool.nextBuffer(IntBlockPool.java:155)
    at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:158)
    at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:661)
    at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:344)
    at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:300)
    at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
    at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
    at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1475)
    at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1254)
    at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:539)
    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:468)
    ... 11 more
[2015-12-17 00:20:59,820][WARN ][index.engine             ] [Howard the Duck] [840dbd219e778253ea7d0000c90125ce][0] failed engine [refresh failed]
java.lang.OutOfMemoryError: Java heap space
    at org.apache.lucene.util.fst.BytesStore.writeByte(BytesStore.java:91)
    at org.apache.lucene.util.fst.FST.<init>(FST.java:296)
    at org.apache.lucene.util.fst.Builder.<init>(Builder.java:172)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$PendingBlock.compileIndex(BlockTreeTermsWriter.java:594)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.writeBlocks(BlockTreeTermsWriter.java:775)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.finish(BlockTreeTermsWriter.java:1114)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter.write(BlockTreeTermsWriter.java:461)
    at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.write(PerFieldPostingsFormat.java:198)
    at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:107)
    at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:112)
    at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:422)
    at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
    at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
    at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:423)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
    at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
    at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:123)
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:137)
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
    at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
    at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:678)
    at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:615)
    at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1255)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2015-12-17 00:21:02,316][DEBUG][action.admin.indices.mapping.put] [Howard the Duck] failed to put mappings on indices [[840dbd219e778253ea7d0000c90125ce]], type [mail]
ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping [mail]) within 30s]
    at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:290)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2015-12-17 00:21:02,317][WARN ][index.shard              ] [Howard the Duck] [840dbd219e778253ea7d0000c90125ce][0] Failed to perform scheduled engine refresh
[840dbd219e778253ea7d0000c90125ce][[840dbd219e778253ea7d0000c90125ce][0]] RefreshFailedEngineException[Refresh failed]; nested: OutOfMemoryError[Java heap space];
    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:686)
    at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:615)
    at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1255)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at org.apache.lucene.util.fst.BytesStore.writeByte(BytesStore.java:91)
    at org.apache.lucene.util.fst.FST.<init>(FST.java:296)
    at org.apache.lucene.util.fst.Builder.<init>(Builder.java:172)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$PendingBlock.compileIndex(BlockTreeTermsWriter.java:594)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.writeBlocks(BlockTreeTermsWriter.java:775)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter$TermsWriter.finish(BlockTreeTermsWriter.java:1114)
    at org.apache.lucene.codecs.blocktree.BlockTreeTermsWriter.write(BlockTreeTermsWriter.java:461)
    at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsWriter.write(PerFieldPostingsFormat.java:198)
    at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:107)
    at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:112)
    at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:422)
    at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
    at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:615)
    at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:423)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:286)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:261)
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:251)
    at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
    at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:123)
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:137)
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
    at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
    at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:678)
    ... 5 more
```

**Comment by extremeshok** [comment]
/etc/elasticsearch/elasticsearch.yml

```
# Lock the memory on startup:
bootstrap.mlockall: true
# Disable starting multiple nodes on a single system:
node.max_local_storage_nodes: 1
bootstrap.sigar: false
# limit the cache size
indices.fielddata.cache.size:  40%
index.number_of_shards: 1
index.number_of_replicas: 0
```

**Comment by atkinsj** [comment]
We push data to ES through the _bulk API -- 15MB at a time. It seems unusual that that would be too much for your configuration, I'm testing on a VM with a default configuration of ES and 4GB of RAM.

I'll see if I replicate it with some different data types and see how I go.

**Comment by extremeshok** [comment]
Do you set any limits for java or anything ?

The index will reindex for maybe 10mins before going into a OOM and if we dont reindex, regular dovecot-imap causes an OOM in 30mins.

**Comment by atkinsj** [comment]
Our servers so have an ES_HEAP_SIZE over the default as per
https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html
.

It really shouldn't crash under OOM due to heap size like that, though.
What version of ES are you running? I suspect upping your heap size is just
going to result in a longer time before crashing.

I'm spinning it up on a large data set now and I'll experiment dropping the
bulk index size and making the refreshes more lazy. I'll let you know.

**Comment by extremeshok** [comment]
Elasticsearch from their elasticsearch-2.x/ repo.

2.1.1-1

**Comment by geekpete** [comment]
If you have 64gb of ram, then the general patter is to allocate half to the Elasticsearch heap, but there is a limit you should avoid going over. To know the best specific setting for Elasticsearch heap this great blog post covers the issues: https://www.elastic.co/blog/a-heap-of-trouble

There's also been many great changes in recent Elasticsearch versions around memory usage as well as performance, though this plugin might need some work to come up to the latest supported Elasticsearch version.

**Comment by atkinsj** [comment]
Cleaning up old issues. Let me know if you're still experiencing issues.
